runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app


libraries:
- name: flask
  version: 0.12
- name: requests
  version: 2.8.1

- name: chardet
  version: 2.3.0

- name: chardet
  version: 2.3.0
